version = "1.3.0"
builder = "spa"

[template_settings]
text-color = "#49120a"
accent-color = "#bb2416"
background-color = "#121414"
highlight-color = "#49120a"
autoreload = "1"
custom-color = "#f3a833"
youtube-embed-params = "autoplay=1"
